### ISSUE TITLE
Grammatical error

### ISSUE THREAD

**Issue by devinrhode2** [emberui/website#10]
http://www.emberui.com/documentation "What it will do is provide you a set of polished UI components that will make building great apps _must_ faster."

This website repo readme says it's moved to the main repo but I do not see where the documentation for this page is to submit an actual PR

**Comment by jacojoubert** [comment]
The documentation is located under `/tests/dummy/`. There is a full fledged ember app in there per ember-cli addon's structure. I suggest you look at the `api-refactor` branch since a ton of changes has been made as of late.

**Comment by devinrhode2** [comment]
I think it would be good to document the location of the documentation

-Devin http://devinrhode2.github.io
http://zerply.com/devinrhode2

**Comment by devinrhode2** [comment]
Maybe even put a link in the live docs that goes to the documentation code
in github. Maybe in the footer or a type of 'fork on github' thing

-Devin http://devinrhode2.github.io
http://zerply.com/devinrhode2

**Comment by jacojoubert** [comment]
Agreed. I will update the readme on the main repo.
